---
- name: Close Ticket - SNOW
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev216600.service-now.com"
    servicenow_username: "{{ snow_username | default('admin') }}"
    servicenow_password: "{{ snow_password | default('!') }}"
  
  tasks:

   - name: Close Ticket
     servicenow.itsm.incident:
      instance:
       host: "{{ servicenow_instance }}"
       username: "{{ servicenow_username }}"
       password: "{{ servicenow_password }}"
      number: "{{ ticket }}"
      state: closed
      close_code: "Solved (Permanently)"
      close_notes: "Repo Configured"
     register: result
     delegate_to: localhost

   - name: print
     debug:
      msg: "{{ result }}"
