---
- name: Configure controller with new project and templates
  hosts: localhost
  gather_facts: no

  vars:
    github_repo: 
    github_file: 
    github_branch:
    controller_host:
    controller_username:
    controller_password:

  tasks:
  
   - name: Add project
     ansible.controller.project:
       name: "New Repo from SNOW"
       description: "New Repo from SNOW"
       organization: "Default"
       scm_type: git
       scm_url: "{{ github_repo }}"
       state: present
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false

   - name: Add Template
     ansible.controller.job_template:
       name: "Playbook"
       job_type: "run"
       organization: "Default"
       inventory: ""
       project: "Roadshow"
       playbook: "{{ github_file }}"
       execution_environment: "Rhel_ee"
       credentials:
         - "Application Nodes"
       state: "present"
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
