---
- name: Configure controller with new project and templates
  hosts: localhost
  gather_facts: no

  vars:
    code_repo:
    playbook:
    code_branch:
    controller_host:
    controller_username:
    controller_password:

  tasks:
  
   - name: Add project
     ansible.controller.project:
       name: "Montecarlo Repo"
       description: "Repository provided by ServiceNow ticket"
       organization: "Default"
       scm_type: git
       scm_url: "{{ code_repo }}"
       state: present
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false

   - name: Add Template
     ansible.controller.job_template:
       name: "Deploy Montecarlo Simulation Application"
       job_type: "run"
       inventory: "Demo Inventory"
       project: "Montecarlo Repo"
       playbook: "{{ playbook }}"
       organization: "Default"
       execution_environment: "Default execution environment"
       credentials:
         - "Demo Credential"
       state: "present"
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
