---
- name: Configure controller with new project and templates
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev216600.service-now.com"
    servicenow_username: "{{ snow_username | default('admin') }}"
    servicenow_password: "{{ snow_password | default('!') }}"
    ticket_number: "{{ ansible_eda.event.payload.number | default('') }}"
    github_repo_filter: "{{ github_repo | default('') }}"
  
  
  - name: (EXECUTION) Add project
    ansible.controller.project:
      name: "Roadshow"
      description: "Roadshow Content"
      organization: "Default"
      scm_type: git
      scm_url: 
      state: present
      controller_host: "https://localhost"
      controller_username: 
      controller_password: 
      validate_certs: false

  - name: Add OSCAP Setup Template
    ansible.controller.job_template:
      name: "OpenSCAP Report"
      job_type: "run"
      organization: "Default"
      inventory: ""
      project: "Roadshow"
      playbook: "
      execution_environment: "Rhel_ee"
      credentials:
        - "Application Nodes"
      state: "present"
      controller_host: "https://localhost"
      controller_username: 
      controller_password: 
      validate_certs: false
