---
- name: Configure controller with new project and templates
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev216600.service-now.com"
    servicenow_username: "{{ snow_username | default('admin') }}"
    servicenow_password: "{{ snow_password | default('!') }}"
    ticket_number: "{{ ansible_eda.event.payload.number | default('') }}"
    github_repo_filter: "{{ github_repo | default('') }}"
    github_repo: "{{ result.records[0].description | regex_search('Repository: (https://[^\\r\\n]+)', '\\1') | first }}"
    github_file: "{{ result.records[0].description | regex_search('File: ([^\\r\\n]+)', '\\1') | first }}"
    github_branch: "{{ result.records[0].description | regex_search('Branch: ([^\\r\\n]+)', '\\1') | first }}"

  
  
  - name: Add project
    ansible.controller.project:
      name: "New Repo from SNOW"
      description: "New Repo from SNOW"
      organization: "Default"
      scm_type: git
      scm_url: "{{ github_repo }}"
      state: present
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      validate_certs: false

  - name: Add Template
    ansible.controller.job_template:
      name: "Playbook"
      job_type: "run"
      organization: "Default"
      inventory: ""
      project: "Roadshow"
      playbook: "{{ github_file }}"
      execution_environment: "Rhel_ee"
      credentials:
        - "Application Nodes"
      state: "present"
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      validate_certs: false
