---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Incident detected
      condition: event.payload.state == "1"
      action:
       run_workflow_template:
        name: "Application Deployment Workflow"
        organization: Default
        post_events: true
