---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: backup all switches
      condition: event.payload.state == "-5"
      action:
       run_playbook:
        name: response.yml
        post_events: true
